
export const UPDATE_ACCOUNT_SUCCESSFUL = "UPDATE_ACCOUNT_SUCCESSFUL";
export const UPDATE_ACCOUNT_UNSUCCESSFUL = "UPDATE_ACCOUNT_UNSUCCESSFUL";
export const PROFILE_IMAGE_UPLOAD_SUCCESSFUL = "PROFILE_IMAGE_UPLOAD_SUCCESSFUL";

export const LOAD_USER = "LOAD_USER";